### ISSUE TITLE
Cannot Find Input File

### ISSUE THREAD

**Issue by khaledJabr** [SouhirG/NERAr#1]
Hello I followed the instructions of use and I keep getting this error 

`./segment+detect.geo+pretrad.geo.sh text_ar.txt`

``
Translitteration...
Tokenization...
Wapiti...
Load model
error: cannot open input data file
	<No such file or directory>
Normalization...
Segmentation...
Named Entities Recognition...
Load model
Label sequences
Done
0 localisations pour lesquelles des traductions sont proposées
0 personnes pour lesquelles des traductions sont proposées
0 organisations pour lesquelles des traductions sont proposées
Processing Done
``

Any suggestions ?

**Comment by SouhirG** [comment]
Hi,

Did you install Wapiti and follow instructions as shown in the Readme ?

1- cd ~/wapiti/NERAr

2- ./segment+detect.geo+pretrad.geo.sh arabic_filename

**Comment by khaledJabr** [comment]
I apologize for my late response. Yes, I followed the the instructions in the readme file and I am still getting the same error. It is having an issue finding the input file `arabic_filename`

**Comment by SouhirG** [comment]
Hi,

Can you send me your arabic file to test it ?

Thanks 
Souhir
